services:
  - type: web
    name: bilibili-downloader-api
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON_BASE64
        sync: false
      - key: GOOGLE_OAUTH_TOKEN_JSON_BASE64
        sync: false
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false
      - key: GOOGLE_DRIVE_SHARE_PUBLIC
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
